### PR TITLE
Implemented exposed iterables

### PR DESCRIPTION
**Pull request by dusansimic**
Implemented exposed iterables as suggested in #40. Also added a function
_removeKeyPrefix so it's easy to remove prefix from key when returning
it in an iterable. Tests are added too for all three functions(keys,
values, entries).

Ref: https://github.com/lukechilds/keyv/issues/40

### CODE REVIEW

**Comment by thgh** [comment]
Can I help to get this merged?

**Comment by rubenmoya** [comment]
I'd love to see this merged, is there anything missing in the PR? Anything we can help with?

**Comment by lukechilds** [comment]
I'm not sure this is the correct way to go about this.

@chocolateboy has some vary valuable feedback here: https://github.com/lukechilds/keyv/issues/40#issuecomment-444632656

What are your thoughts?

**Comment by lukechilds** [comment]
@TehShrike also has some valuable input here: https://github.com/lukechilds/keyv/issues/36#issuecomment-452739855

**Comment by dusansimic** [comment]
I think @chocolateboy is right about that. We should do async iteration over keys/values/entries. Should we use the fallback version of iterating over entries or use Babel and use the ES2018 syntax (`for await`).

Also, should the iteration work like [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) function on arrays or should predicate break the iteration? Filter like approach would still have to iterate over all of the entries but it also seem a bit more natural to me. Any thoughts on this?

**Comment by lukechilds** [comment]
>Should we use the fallback version of iterating over entries or use Babel and use the ES2018 syntax (for await).

I'm not familiar with the fallback version, could you provide a tiny code example? I'd like to avoid Babel if possible but if `for await` would be a huge reduction in code complexity then I'd be open to it.

>Also, should the iteration work like filter function on arrays or should predicate break the iteration? Filter like approach would still have to iterate over all of the entries but it also seem a bit more natural to me. Any thoughts on this?

Sorry, not too sure I understand what you mean about a predicate. We should just allow `.keys()`, `.values()`, `.entries()` style methods something like in https://github.com/lukechilds/keyv/issues/40#issue-278444793.

If the users want's to filter for something while they're looping, that's up to them to implement.

Also, have you thought about how we can ensure these methods are atomic across storage adapters: https://github.com/lukechilds/keyv/issues/40#issuecomment-452929583

**Comment by dusansimic** [comment]
> I'm not familiar with the fallback version, could you provide a tiny code example? I'd like to avoid Babel if possible but if `for await` would be a huge reduction in code complexity then I'd be open to it.

This is @chocolateboy s code that can be used as fallback instead of ES2018. `for await` does make code more readable and shorter but in general, it's the same thing.
``` javascript
async function any (keyv, predicate) {
    const it = keyv.entries()[Symbol.asyncIterator]()

    while (true) {
        const { done, value: pair } = await it.next()

        if (done) {
            return false
        }

        if (predicate(...pair)) {
            return true
        }
    }
}
```
But still, this is what user implements so, we shouldn't care much. If I understand the comments correctly, our goal i just to return an iterator which user can use to iterate over elements.

> Also, have you thought about how we can ensure these methods are atomic across storage adapters: [#40 (comment)](https://github.com/lukechilds/keyv/issues/40#issuecomment-452929583)

For storage adapters, cursor could be used. I think all databases that storage adapters use have that feature (for SQL and MongoDB it's cursor and for Redis its scan function). Any thoughts on this?

**Comment by chocolateboy** [comment]
> But still, this is what user implements so, we shouldn't care much.

That's right. Whether to use Babel/TypeScript or a JS engine which supports `for await` (which at this point is [everything but IE11/Edge](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#Browser_compatibility)) is a decision  for the *consumer* of the API.

It doesn't need to concern backends unless they a) elect to use *async* generators (if not, `for await` [works with synchronous iterables](http://2ality.com/2017/12/for-await-of-sync-iterables.html), so a backend can just return an ES6 collection or a plain old array) and b) want to support legacy browsers, in which case the *generator* can either be transpiled or written in longhand.

**Comment by chocolateboy** [comment]
Incidentally, for Keyv v3, it would probably make sense for the API to restrict itself to synchronous iterables, rather than documenting/supporting the async usage. Why? Because the current API (`get`, `set`, `delete`, `clear`) is synchronous.

If/when a move to asynchronous iterables is made, e.g. for v4, the current API should be upgraded as well, IMO, i.e. `get`, `set`, `delete`, `clear` etc. should all return promises.

In practice, this doesn't mean every backend must be inherently async. It just means a backend *can* be async. As with async iterables, the synchronous behavior can be thought of as a subset/special case of the async API.

There's some prior art for this transition/migration in [Greasemonkey v3.0 -> v4.0](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html).

**Comment by lukechilds** [comment]
@dusansimic

>But still, this is what user implements so, we shouldn't care much. If I understand the comments correctly, our goal i just to return an iterator which user can use to iterate over elements.

Ah sorry, I misunderstood you, yeah, there is no `.any()` method on map, it shouldn't be implemented inside Keyv. I think @chocolateboy was giving an example of how user code would interact with the `.keys()`, `.values()` and `.entries()` Keyv methods.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

>For storage adapters, cursor could be used. I think all databases that storage adapters use have that feature (for SQL and MongoDB it's cursor and for Redis its scan function). Any thoughts on this?

Yeah, the issue is making sure it works atomically, or if not possible across all storage adapters, then consistently. e.g, if they start looping over `.entries()` and then a new key gets inserted to the DB during the iteration, what happens? Does the entry get missed because it wasn't there at the beginning? Does it get missed or included depending on where the user is in the iteration when the key was inserted?

The specific behaviour isn't too important, what's important is that it's consistent across storage adapters.

@chocolateboy 

>Incidentally, for Keyv v3, it would probably make sense for the API to restrict itself to synchronous iterables, rather than documenting/supporting the async usage. Why? Because the current API (get, set, delete, clear) is synchronous.
>
>If/when a move to support asynchronous iteration is made, e.g. for v4, the current API should be upgraded as well, IMO, i.e. get, set, delete, clear etc. should all return promises.
>
>In practice, this doesn't mean every backend must inherently be async. It just means a backend can be async. As with async iterables, the synchronous behavior can be thought of as a trivial subset/special case of the async API.

That's already hoy Keyv works. It's already fully async, notice the `await` in the readme example:

```js
const Keyv = require('keyv');

// One of the following
const keyv = new Keyv();
const keyv = new Keyv('redis://user:pass@localhost:6379');
const keyv = new Keyv('mongodb://user:pass@localhost:27017/dbname');
const keyv = new Keyv('sqlite://path/to/database.sqlite');
const keyv = new Keyv('postgresql://user:pass@localhost:5432/dbname');
const keyv = new Keyv('mysql://user:pass@localhost:3306/dbname');

// Handle DB connection errors
keyv.on('error', err => console.log('Connection Error', err));

await keyv.set('foo', 'expires in 1 second', 1000); // true
await keyv.set('foo', 'never expires'); // true
await keyv.get('foo'); // 'never expires'
await keyv.delete('foo'); // true
await keyv.clear(); // undefined
```

https://github.com/lukechilds/keyv#usage

**Comment by chocolateboy** [comment]
@lukechilds

> That's already how Keyv works. It's already fully async

Ah, great! I guess the [API documentation](https://github.com/lukechilds/keyv#instance) just needs updating:

- .set(key, value, [ttl])

> Returns true.

- .get(key, [options])

> Returns the value.

- .delete(key)

> Returns true if the key existed, false if not.

- .clear()

> Returns undefined.

**Comment by lukechilds** [comment]
>Ah, great! I guess the API documentation just needs updating:

Woops, it does indeed, good spot!

**Comment by officialpiyush** [comment]
Any updates on this?

**Comment by dusansimic** [comment]
Hi @officialpiyush. I'm sorry that this issue is pr is inactive for such a long time. I didn't have enough time to fully invest in this and find a good solution.

The current state of my findings is that some database drivers that are used by keyv do not support exposed iterables and some don't even support cursors at all. The second problem which I didn't yet get to is checking if the behavior of drivers (iterables) is consistent across databases which is a deal breaker weather this will be implemented.

Right now I don't have much free time to work on this either so if someone else is interested in taking a shot at this, they're more than welcome. My suggestion would be that if it's needed, change the database driver used in the keyv storage adapters in order to have a better api and better features for work with this. It's far easier to just change the driver and tray to maintain consistency with the previous versions of keyv than try to work with inconsistent drivers.

**Comment by thgh** [comment]
Do you have an overview of which adapters can/cannot handle this?

As I only need SQL adapters, I'm probably better off using knex?

**Comment by dusansimic** [comment]
@thgh, currently no adapter is handling this, it needs to be implemented. As for sql database drivers, MySQL driver (mysql2) has some mentions of exposing iterables but I didn't test anything yet. Postgres driver (pg) has support for cursors and we might be able to implement an iterable with this. SQLite3 driver (sqlite3) does not support either iterables or any cursor implementation AFAIK. It either needs to be implemented using get method (return one entry) or we need to switch the database driver to for example `better-sqlite3` which seems to support iteration over results.

Knex is, if I understand correctly, a query builder, not a driver. Knex can build queries but it cannot execute them by itself, it uses the database driver behind the scenes.

**Comment by Kikobeats** [comment]
Implemented at https://keyv.js.org 👍

**Pull request closed without merging**
